### ISSUE TITLE
Decision and Utility Nodes

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#10]
Decision nodes act like regular random variables.  Only later functions like MEU() (maximum expected utility) will leverage the fact that they are decision nodes (e.g., creating a policy matrix).  So we just need to the following for decision nodes:

1) Create a list object within the HydeNetwork object that stores which nodes are decision nodes.
2) Modify the plot method for HydeNetwork objects to make decision nodes square with white background and some color text
3) Modify the plot method for compiledHydeNetwork objects to make _observed_ decision nodes square with some color background.  Could simply invert the colors above in (2).

Utility nodes are a little trickier.
- They are part of the graph object, but never get fed into JAGS since they're not random variables.  
- They are numeric vectors, all of which are the same length and all of which have the same "slots" (e.g., cost in first slot, QALYs in second slot)
- They are defined by functions, not models.  The functions must map all combinations of parent nodes to a vector utility
- We should probably restrict naming of utility nodes to something like U1, U2, U3, ... because of the above restrictions.
- To visualize utility nodes, I'd say use gray (to denote they are fixed) with triangle shape.

**Comment by nutterb** [comment]
Decision nodes are implemented in 0.7.2.  

For utility nodes, I suppose I only need to add a Utility flag?

**Comment by jarrod-dalton** [comment]
Well, they need to be deterministic functions of parent nodes which produce numeric vectors.  They aren't allowe to have children.  And, all utility nodes in the network need to produce utility vectors with the same number of dimensions.  

On the last point, some little function or function argument or list element or whatever which allows the user to put labels on the "slots" within the utility vectors (e.g. c("cost", "qalys")) might be helpful.

That's what currently comes to mind, at least.

**Comment by nutterb** [comment]
Utility nodes exist in version 0.7.3

**Comment by j-e-dalton** [comment]
Not that it matters much, but I thought I’d mention gRbase::children() as a potential function to use in your error checking for utility nodes within setNode():

net <- HydeNetwork(~ card1.ace | card1
                   + card2.ace | card2
                   + initialPoints | card1_card2_card1.ace_card2.ace
                   + hit1 | initialPoints_dealerUpcard
                   + card3 | hit1
                   + card3.ace | card3
                   + pointsAfterCard3 | initialPoints_card3_card3.ace
                   + hit2 | pointsAfterCard3_dealerUpcard
                   + card4 | hit2
                   + card4.ace | card4
                   + pointsAfterCard4 | pointsAfterCard3_card4_card4.ace
                   + hit3 | pointsAfterCard4_dealerUpcard
                   + card5 | hit3
                   + card5.ace | card5
                   + pointsAfterCard5 | pointsAfterCard4_card5_card5.ace
                   + playerFinalPoints | initialPoints_hit1_pointsAfterCard3
                                         _hit2_pointsAfterCard4_hit3_pointsAfterCard5
                   + dealerFinalPoints | dealerUpcard
                   + payoff | playerFinalPoints*dealerFinalPoints)

plot(g)

children("payoff", net$dag)
##NULL

children("initialPoints", net$dag)
##[1] "hit1"              "pointsAfterCard3"  "playerFinalPoints"

**Comment by j-e-dalton** [comment]
Installed updated package and it can't find the setUtilityNodes function.  Do the lines

  #' @rdname setUtilityNodes
  #' @export

need to be added?

**Comment by jarrod-dalton** [comment]
With version 0.8.0, it can find the function and appears to run it. However, the list element network$nodeUtility does not appear to get populated:

```
net <- HydeNetwork(~ card1.ace | card1
                   + card2.ace | card2
                   + initialPoints | card1*card2*card1.ace*card2.ace
                   + hit1 | initialPoints*dealerUpcard
                   + card3 | hit1
                   + card3.ace | card3
                   + pointsAfterCard3 | initialPoints*card3*card3.ace
                   + hit2 | pointsAfterCard3*dealerUpcard
                   + card4 | hit2
                   + card4.ace | card4
                   + pointsAfterCard4 | pointsAfterCard3*card4*card4.ace
                   + hit3 | pointsAfterCard4*dealerUpcard
                   + card5 | hit3
                   + card5.ace | card5
                   + pointsAfterCard5 | pointsAfterCard4*card5*card5.ace
                   + playerFinalPoints | initialPoints*hit1*pointsAfterCard3
                                         *hit2*pointsAfterCard4*hit3*pointsAfterCard5
                   + dealerFinalPoints | dealerUpcard
                   + payoff | playerFinalPoints*dealerFinalPoints)
net <- setDecisionNodes(net, hit1, hit2, hit3)
net <- setUtilityNodes(net, payoff)

net$nodeUtility
NULL
```

**Comment by nutterb** [comment]
That's because I seem to have named it nodeUtlity. I'll fix the spelling in the morning
