### ISSUE TITLE
We may need to reconsider the name again

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#17]
There is a popular website generator written in python called Hyde.  Will we create confusion about what this package does if we call it `Hyde`?

**Comment by j-e-dalton** [comment]
Ugh.  And I thought Hyde was clever.

Here are some possibilities that don't appear to be on CRAN currently, in no particular order:

HydeNet
hbn
hybrid
bayesNets
hybridNets
mcmcbn
bdn

I won't bias your judgment - which ones do you like most?

**Comment by j-e-dalton** [comment]
On the other hand, yes, we may create confusion, but is it not extremely clever marketing to use 'Hyde'?

**Comment by nutterb** [comment]
I like Hyde, too.  But I want to be sure that 1) you are comfortable that people will know what it is, and 2) we don't lead people into thinking we've done something we haven't.

I think HydeNet is a simple enough modification to make it work.

**Comment by nutterb** [comment]
While we're both active on this, have you made a decision on this yet?  If I hear from you in the next 15 minutes, I can change the name before I upload my changes.

**Comment by nutterb** [comment]
Changed to HydeNet
