### ISSUE TITLE
There needs to be a better package description

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#18]
The package description in the DESCRIPTION file needs to be written.  

The text in the `Title:` field will appear next to the package name on the CRAN listing and in bold at the top of the package summary on CRAN [example](http://cran.r-project.org/web/packages/redcapAPI/index.html).  It should be no more than one line, and give a good idea of what the package does.  Perhaps "Hybrid Decision Graphical Networks Using R and JAGS"

The text in the `Description:` field is what will appear on CRAN next to the package.  It may be multiple lines.  It should explain why someone would be interested in using the package, and should not start with the words 'the package' (Professor Ripley will sometimes criticize vague descriptions)

**Comment by j-e-dalton** [comment]
Updated.  Check it out and see if there is anything to modify.  Regarding you be listed as the maintainer,  does that mean people will bug you forever, and are you okay with that?

**Comment by nutterb** [comment]
That description looks good.  Thanks.

I don't mind being the maintainer.  Most users will probably use the bug report link in the description.  I occassionally get e-mails from CRAN to make sure the maintainer e-mail address is still valid.  But I've never received much traffic from there.

When you pick up a new programmer for the package, we can turn over the reins then.
