### ISSUE TITLE
Error on default call of HydeNetwork()

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#19]
I can't remember if this was a known issue or not, but I thought I'd post just in case it wasn't:

When HydeNetwork() is run with the PE training dataset, it produces an error:

> data(PE, package='Hyde')
> autoNet <- HydeNetwork(~ wells
>                         + pe | wells
>                         + d.dimer | pregnant_pe
>                         + angio | pe
>                         + treat | d.dimer_angio
>                         + death | pe_treat,
>                         data = PE)
> Error in `[[<-`(`_tmp*`, which(sapply(nodeFitter, function(x) x == "glm")),  : 
>   no such index at level 2

I think the error has to do with indexing within the nodeFitterArgs object at about line 103, where it tries to populate the family='binomial' argument for glm().

The weird thing is that when I step through HydeNetwork.formula(), the error doesn't show up.

**Comment by nutterb** [comment]
I can't replicate this error.  Try

``` r
devtools::install_github("nutterb/Hyde", ref="development")
HydeNetwork(~ wells
                       + pe | wells
                       + d.dimer | pregnant*pe
                       + angio | pe
                       + treat | d.dimer*angio
                       + death | pe*treat,
                       data = PE)
```

I think you might not have updated the package from a prior update.

**Comment by j-e-dalton** [comment]
That did the trick.
