### ISSUE TITLE
univariate distributions now getting warning

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#22]
Not sure if this is related to argument processing in setNode after implementing setNodeModels, but I now get a warning message:

net <- HydeNetwork(~ wells
- pe | wells
- d.dimer | pregnant*pe
- angio | pe
- treat | d.dimer*angio
- death | pe*treat)

net <- setNode(network = net, node = pregnant, nodeType = "dbern", p=.4)
Error in if (wrn.flag) warning(paste(warn.msg, collapse = "\n")) : 
  argument is not interpretable as logical

**Comment by j-e-dalton** [comment]
I reproduced the warning - which actually acts like an error, stopping all action - using the mtcars2 example given in the setNode() documentation.

**Comment by nutterb** [comment]
I know exactly what that is.  I set up the warning buffer as

``` r
wrn.flag <- 0
wrn.flag <- ""
```

That second `wrn.flag` should have been `wrn.msg`
