### ISSUE TITLE
decimals not truncated to 5 in writeNetworkModel(pretty=TRUE)

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#25]
This is a small issue - somehow the parameters for node 'wells' were not printed with 5 digits.  no biggie...

data(PE, package='HydeNet')
autoNet <- HydeNetwork(~ wells
                       + pe | wells
                       + d.dimer | pregnant_pe
                       + angio | pe
                       + treat | d.dimer_angio
                       + death | pe*treat,
                       data = PE)
writeNetworkModel(autoNet, pretty=TRUE)

**Comment by nutterb** [comment]
Fixed
