### ISSUE TITLE
update.HydeNetwork method & parent nodes

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#28]
What should be the default behavior for update() when we are trying to remove parent nodes?

One option would be to make the user specify the removal of BOTH the parent node and the link to all child nodes (e.g., ". ~ . - pregnant - d.dimer | pregnant").  This seems cumbersome.

Another option would be to only have the user specify minimal syntax but give warning messages:

net2 <- update(net, . ~ . - pregnant)

warning in update.HydeNetwork(): 
   Node 'pregnant' had the following child node(s): 'd.dimer'.
   Conditional probability distributions have been removed from these nodes.
   Use 'setNode()' or 'setNodeModels()' to repopulate these distributions.

**Comment by j-e-dalton** [comment]
If we went with the warning message approach, the warnings would be more "smartly" given if a logic check was first done to ensure that the distributions for child node(s) are not unspecified.  In other words, if we are using HydeNetwork.formula() with no training dataset and then using update() and plot() interactively to construct the graph -- prior to populating nodes with distributions -- then we should not need to see a warning message.

**Comment by nutterb** [comment]
I've done some work on this.  The current code will check to see if any parents have been lost and print an appropriate warning.

``` r
library(HydeNet)
data(PE, package='HydeNet')
autoNet <- HydeNetwork(~ wells
                       + pe | wells
                       + d.dimer | pregnant*pe
                       + angio | pe
                       + treat | d.dimer*angio
                       + death | pe*treat,
                       data = PE)

plot(autoNet)

autoNet2 <- update(autoNet, . ~ . - treat)
plot(autoNet2)

autoNet3 <- update(autoNet, . ~ . - pregnant)
plot(autoNet2)

autoNet4 <- update(autoNet, . ~ . - treat - pregnant)
plot(autoNet4)
```

However, it does not check for whether the lost parent is actually used in the child node.  I began looking at this, and to do it would required parsing formulae in the `nodeFormula` attribute as well as parsing the `nodeParams` attribute.  It is further complicated by the need for an exact match.  We don't want to match 'pre' as a missing parent when we also have a node called `pregnant`.  

I'll leave this open for now and may come back to it later, but for now the user will at least be notified if he or she has deleted a parent node entirely.

**Comment by nutterb** [comment]
I've been revisiting this and I'm going to close it.  I can't see a way to parse out more information to pass to the user without going into a rabbit hole I may never come out of.  And I think the current warning gives enough information to the user to be able to remedy the situation.
