### ISSUE TITLE
Question on Policy Matrices

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#34]
Would it be fair to characterize policy matrices as a potential subset of all possible combinations of decisions from the set of decision networks?

I'm wondering if I can use the same infrastructure of the decision networks in the policy matrices.

**Comment by jarrod-dalton** [comment]
Yes it is fair, with the caveat that we need to also allow for decision nodes to be unspecified in the policy matrix (by missing values?).  For example, suppose we have a network with a disease node, a treatment decision node, and outcome node. There are also decision nodes reflecting the decision to do various diagnostic tests.  Here, we might seek some "optimal" policy of which tests to perform, independent of the later treatment decision.  We should in this case treat the treatment decision as a regular random variable.

We should think in greater detail about this specific example, even to the point of working through it within the influence diagram vignette.  

As for your latter sentence, I couldn't make any sense out of it.

**Comment by nutterb** [comment]
Okay, so I'm leaving this note here so that I remember to fix this part.  It's a pretty glaring omission.

We have a way to generate posteriors for all of the various permutations of a decision network, based on the decision nodes.  We have a way of generating policy matrices.  But we have no way of feeding the policy matrix to `compileDecisionNetwork` to run only the policies we're interested in.  

Oops.
