### ISSUE TITLE
JAGS parse error with compileJagsModel 

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#35]
g1 <- lm(wells ~ 1, data=PE)
g2 <- glm(pe ~ wells, data=PE, family="binomial")
g3 <- lm(d.dimer ~ pe + pregnant, data=PE)
g4 <- xtabs(~ pregnant, data=PE)
g5 <- glm(angio ~ pe, data=PE, family="binomial")
g6 <- glm(treat ~ d.dimer + angio, data=PE, family="binomial")
g7 <- glm(death ~ pe + treat, data=PE, family="binomial")

bagOfModels <- list(g1,g2,g3,g4,g5,g6,g7)

bagNet <- HydeNetwork(bagOfModels)

> compiled.bagNet <- compileJagsModel(bagNet, n.chains=3)
> Error in rjags::jags.model(textConnection(writeNetworkModel(network)),  : 

Error parsing model file:
syntax error on line 2 near "~"

**Comment by nutterb** [comment]
Fixed in 0.7.3
