### ISSUE TITLE
Deterministic node type declaration requires running setNode()

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#40]
Currently, if I'm not mistaken, you have to do the work of populating all the node distributions in the network before you can take advantage of all the fancy `plot.HydeNetwork()` defaults for visualization. 

Sometime, we should think about giving users the capacity to declare node types for all nodes in the network up front, so that they can use the plot method without needing to use `setNode()` to say which nodes are deterministic in nature.

**Comment by nutterb** [comment]
As long as there's a `HydeNetwork` object, the user could always run `setDecisionNodes` and `setUtilityNodes` to turn on the flags for decision and utility nodes.  The thing we can't do right now is set deterministic nodes. But that could be as constructing another `setDetermNodes` function to set the nodeType in batch and put in a generic definition for the `nodeParam`.

```
data(PE, data="HydeNet")
Net <- HydeNetwork(~ wells + 
                     pe | wells + 
                     d.dimer | pregnant*pe + 
                     angio | pe + 
                     treat | d.dimer*angio + 
                     death | pe*treat) 
Net <- setDecisionNodes(Net, treat)
Net <- setUtilityNodes(Net, d.dimer)

plot(Net)
```

**Comment by jarrod-dalton** [comment]
`setDecisionNodes()` and `setUtilityNodes()` have actual analytic functionality.

A function `setDetermNodes()` would only indicate which nodes should be plotted in light gray.

Would it be better to have an optional character vector parameter in `plot.HydeNetwork()` called `determ=` which allows the user to feed the names of the deterministic nodes?  I guess that, to get around any inconsistencies, priority should be given to this parameter over the node types in `plot.HydeNetwork()` if this parameter is specified.  Just an idea...

Which approach would be more confusing?  I guess the filp side to this point is that users might wonder why no `decision=` and `utility=` parameters in `plot.HydeNetwork()` existed.  So I don't know...
