### ISSUE TITLE
Hide deterministic nodes in plot.HydeNetwork()

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#44]
Realize that I'm coming up with a bunch of stuff with the expectation that very little of it will be incorporated into Version 1.0.  So let's stay on track with the current plan of getting v1.0 out.  But I digress...

It occurred to me that users might want to just visualize random variables, decision nodes, and utilities.

Maybe there's already a function that will generate a subnetwork of a DAG.  It's actually a little challenging. I came up with the following (naive and slow) algorithm:

```
for each 'determ' node D_j:
|  make a link between all children of D_j and all parents of D_j
|  delete the node D_j and all links involving D_j (both incoming and outgoing)
end for
```

I investigated whether or not there are actually functions that do this.  I'm sure there are.  I found something useful in the `igraph` library but it doesn't give us exactly what we want.  It looks like the `induced.subgraph()` algorithm just includes edges that existed among included vertices. That totally makes sense.  Maybe the `igraph` package has something that will do it though.  

Or maybe a home-cooked algorithm on the adjacency matrix will be best.  I don't know.

```
require(igraph)

g <- dag(~ card1.ace | card1
         + card2.ace | card2
         + initialPoints | card1*card2*card1.ace*card2.ace
         + hit1 | initialPoints*dealerUpcard
         + card3 | hit1
         + card3.ace | card3
         + pointsAfterCard3 | initialPoints*card3*card3.ace
         + hit2 | pointsAfterCard3*dealerUpcard
         + card4 | hit2
         + card4.ace | card4
         + pointsAfterCard4 | pointsAfterCard3*card4*card4.ace
         + hit3 | pointsAfterCard4*dealerUpcard
         + card5 | hit3
         + card5.ace | card5
         + pointsAfterCard5 | pointsAfterCard4*card5*card5.ace
         + playerFinalPoints | initialPoints*hit1*pointsAfterCard3
         *hit2*pointsAfterCard4*hit3*pointsAfterCard5
         + dealerFinalPoints | dealerUpcard
         + payoff | playerFinalPoints*dealerFinalPoints)

#coerce dag to igraph object

h <- gRbase::coerceGraph(g, "matrix")
j <- igraph::graph.adjacency(h, mode="directed")

keepNodes <- c("card1","card2","hit1","card3","hit2","card4","hit3",
               "card5","dealerUpcard","dealerFinalPoints","payoff")
k <- igraph::induced.subgraph(j,vids = which(V(j)$name %in% keepNodes))

#plot(j, layout=layout.sphere)
#plot(k, layout=layout.kamada.kawai)



jj <- as(get.adjacency(j), "graphNEL")
kk <- as(get.adjacency(k), "graphNEL")

plot(jj, attrs=list(node=list(shape="ellipse", fixedsize=FALSE)))
plot(kk, attrs=list(node=list(shape="ellipse", fixedsize=FALSE)))
```

![image](https://cloud.githubusercontent.com/assets/11472793/7443033/0d2fe816-f0fc-11e4-83ca-7a9418c3934e.png)

![image](https://cloud.githubusercontent.com/assets/11472793/7443035/1e6e14fe-f0fc-11e4-936b-570583c096df.png)

**Comment by nutterb** [comment]
Would this be as simple as passing a list of nodes you want to view and only plotting those nodes and their relationships to each other?  Cause that could be done very easily.  We would just need to pull those nodes out of the nodes list and grab those parents and run it through `plot.HydeNetwork`.

**Comment by jarrod-dalton** [comment]
Assume a --> b --> c is the graph and b is deterministic.  If we want to delete b, we would need to link all parents to all children of b.

We also might want to hide nodes according to certain rules, such as all nodes not (currently) d-separated from node Z.

I will research this some more and post some further ideas.

**Comment by nutterb** [comment]
I see now.  I don't think it would be too hard to write something to do this.  It would go something like
1. for each node, scan the parent `nodeTypes`.
2. for any `nodeType=='determ'`, replace the parent with the vector of super parents.
3. use the nodes and parents of the non-deterministic nodes to generate a formula for the new `HydeNetwork` in the local environment.
4. construct the new `HydeNetwork` and reassign decision and utility nodes
5. plot the new network

The big question is if you want to be able to save the network from the local environment, or if it can be disposed of after the plotting is complete.

**Comment by nutterb** [comment]
The solution I'm about to commit is home-brewed.  It might not be terribly efficient because it uses a `while` loop to run up the chain of parents until it finds none that are deterministic.  I might have been able to make something more efficient using `igraph`, but I have so many problems related to `igraph`'s dependency on `RBGL` that if I ever figure out how to ditch `igraph`, I will do it in a heartbeat (unfortunately, that would mean also ditching `gRbase`, which would require rewrite the `dag` function, so it's probably a pipe dream).

Anyway, this is done.
