### ISSUE TITLE
Bug in setNode() - parameter value check for univ distributions

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#5]
net <- setNode(net, d.dimer, nodeType = "dpois", lambda=-10)

This should return an error message like the following:

paste0("Node '", node, "': parameter '", bad.param,"' outside allowable range in '", nodeDist,"' (",jagsDists$paramLimit[jagsDists$FnName==nodeDist],")")

**Comment by nutterb** [comment]
I incorporated a new function `validateParameters` to take care of this.  It also required an additional column in the `jagsDists` data object which gives the R logic to validate the parameter.  

It's a wicked slick implementation, if I do say so myself.
