### ISSUE TITLE
plot.HydeNetwork() showing up in browser

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#50]
Is there an option in DiagrammeR or something that tells R to open a browser window for plot output?

**Comment by nutterb** [comment]
I haven't explored the options but that may be a side effect of getting the full use of GraphViz. On the bright side, Rstudio announced that their next release will support Diagrammer graphics in the IDE. are they appearing in the vignettes correctly?

Also, the preview version of R Studio is available now, if that helps

**Comment by nutterb** [comment]
Yeah, the browser is a inherent behavior of `DiagrammeR`.  I think it's part of the price we pay for getting the full GraphViz API.  The preview version of R Studio puts it in the plots pane.  They appear quite nicely in the rendered vignettes.  I guess it's a matter of choosing which nuisance you want to deal with.

**Comment by jarrod-dalton** [comment]
That's fine.  Thanks for checking into it
