### ISSUE TITLE
Redundancy of utility node specification? Or overkill?

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#53]
This is minor...

Not sure what's going on under the hood, but in the blackjack model I was working on the payoff node.  It's a utility node, defined by a deterministic function.  

Here is what I had:

```
net <- setUtilityNodes(net, payoff)
net <- setNode(net, payoff, "determ", define=fromFormula(),
               nodeFormula = payoff ~ 
                  ifelse(playerFinalPoints > 21,
                     -1,
                     ifelse(dealerFinalPoints > 21,
                        1,
                        ifelse(playerFinalPoints > dealerFinalPoints,
                           1,
                           ifelse(playerFinalPoints == dealerFinalPoints, 0, -1)))))
```

But I ran it another time without the `setUtilityNodes` call, and just had this:

```
net <- setNode(net, payoff, "determ", define=fromFormula(),
               nodeFormula = payoff ~ 
                  ifelse(playerFinalPoints > 21,
                     -1,
                     ifelse(dealerFinalPoints > 21,
                        1,
                        ifelse(playerFinalPoints > dealerFinalPoints,
                           1,
                           ifelse(playerFinalPoints == dealerFinalPoints, 0, -1)))),
                utility = TRUE)
```

That seemed to work, at least with `plot.HydeNetwork()`.  And the network object stored the fact that it was a utility node.

So I guess the problem is that if I run `setUtilityNodes()`, and then run `setNode` without explicitly saying utility=TRUE, then the fact that it was a utility node gets overridden by `setNode`.  This may be conservative behavior which avoids trouble down the line; however, it seems to call into question the, er, utility, of the `setUtilityNodes()` function.

**Comment by nutterb** [comment]
Would it work for you if I changed the default behavior of `setNode`'s `decision` and `utility` nodes from `FALSE` to `"current"`?  The allowable values would then be `"current"', 'TRUE', or 'FALSE'.

**Comment by jarrod-dalton** [comment]
That sounds good.
