### ISSUE TITLE
Do we need to export as many functions as we do?

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#55]
It seems to me that a lot of the functions I've exported aren't really intended to be called by the user.  This is especially true in the case of the methods like `writeJagsFormula`.  I need to figure out how to get these to work without exporting them.

**Comment by jarrod-dalton** [comment]
I agree.  And for some reason, roxygen put a skeleton documentation file for `%>%` into the package. I don't know why it did that, and no idea how to get around it.

**Comment by jarrod-dalton** [comment]
And would it be too confusing if we just mapped all documentation for functions involved with plotting HydeNet objects to the help file for `plot.HydeNetwork()`?

**Comment by jarrod-dalton** [comment]
We could combine the help files for the datasets into a single file, as Hadley does here:

https://github.com/hadley/babynames/blob/master/R/data.R

**Comment by nutterb** [comment]
and it seems the answer is yes, we need to export all of the methods.
