### ISSUE TITLE
Multidimensional Arrays for Discrete CPTs in JAGS

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#58]
Here is a sample JAGS script that uses a multidimensional array object fed from `rjags`:

```
model{
  # Likelihood:
  di1 ~ dcat(priorProbs)
  di2 ~ dcat(priorProbs)

  for ( i in 1:dim1 ) {
    for( j in 1:dim2 ){
      di3[i,j] ~ dcat( probArray[i,j,] )
    }
  }
}
```

Here is the R code used to generate the list object fed to JAGS via `rjags`:

```
n <- 50000 
data <- data.frame(
  di1=as.factor(1:6 %*% rmultinom(n,1,prob=c(.4,.3,.15,.10,.03,.02))),
  di2=as.factor(1:6 %*% rmultinom(n,1,prob=rev(c(.4,.3,.15,.10,.03,.02)))),
  di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
)
cpt <- HydeNet::cpt(di3 ~ di1 + di2, data)


dataList = list(
    dim1 = 6,
    dim2 = 6,
    priorProbs = c(rep(.001->ppp,5),1-ppp),  #rep(1,6),
    probArray = cpt
)
```

(I made the probabilities heavily skewed to di1=6 and di2=6 to check results.) Here is some of the `coda.samples()` posterior matrix:

```
     di1 di2 di3[1,1] di3[2,1] di3[3,1] di3[4,1] di3[5,1] di3[6,1] di3[1,2]
[1,]   6   6        1        5        5        4        1        4        4
[2,]   6   6        4        4        5        5        1        4        5
[3,]   6   6        2        5        4        1        5        4        5
[4,]   6   6        5        1        4        2        4        5        4
[5,]   6   6        4        2        1        5        4        1        4
[6,]   6   6        5        4        1        4        1        4        3
     di3[2,2] di3[3,2] di3[4,2] di3[5,2] di3[6,2] di3[1,3] di3[2,3] di3[3,3]
[1,]        5        5        3        5        2        4        1        2
[2,]        5        5        2        5        2        3        1        5
[3,]        1        2        5        1        1        2        5        5
[4,]        5        5        1        4        2        2        4        4
[5,]        5        2        2        5        4        4        2        4
[6,]        2        6        2        4        1        4        5        1
     di3[4,3] di3[5,3] di3[6,3] di3[1,4] di3[2,4] di3[3,4] di3[4,4] di3[5,4]
[1,]        4        5        4        5        2        4        4        5
[2,]        4        5        1        5        1        5        6        5
[3,]        5        5        5        3        4        1        5        1
[4,]        5        5        4        5        5        5        5        5
[5,]        5        5        4        5        5        5        1        5
[6,]        5        5        1        5        5        5        6        4
     di3[6,4] di3[1,5] di3[2,5] di3[3,5] di3[4,5] di3[5,5] di3[6,5] di3[1,6]
[1,]        5        5        4        1        5        4        5        4
[2,]        5        4        5        5        4        4        5        2
[3,]        5        4        5        4        5        4        5        5
[4,]        4        6        4        4        5        6        1        1
[5,]        6        4        5        5        5        5        4        5
[6,]        6        2        2        4        5        2        4        4
     di3[2,6] di3[3,6] di3[4,6] di3[5,6] di3[6,6]
[1,]        5        2        4        5        4
[2,]        4        4        5        5        5
[3,]        4        5        5        5        5
[4,]        2        5        5        5        1
[5,]        5        1        4        5        4
[6,]        5        4        5        5        5
```

Notice lots of irrelevant samples from `di3`.  The only one that matters is the one indexed by `di1` and `di2` for each respective row of the matrix. To fix this, modify the JAGS code a bit, and don't ask for `di3Sample` when calling `coda.samples()`:

```
model{
  # Likelihood:
  di1 ~ dcat(priorProbs)
  di2 ~ dcat(priorProbs)

  for ( i in 1:dim1 ) {
    for( j in 1:dim2 ){
      di3Sample[i,j] ~ dcat( probArray[i,j,] )
    }
  }

  di3 <- di3Sample[di1, di2]
}
```

This looks better:

```
      di1 di2 di3
 [1,]   6   6   4
 [2,]   6   6   5
 [3,]   6   6   5
 [4,]   6   6   5
 [5,]   6   6   1
 [6,]   6   6   2
 [7,]   6   6   1
 [8,]   6   6   5
 [9,]   6   6   4
[10,]   6   6   4
[11,]   6   6   5
[12,]   6   6   1
[13,]   6   6   5
[14,]   6   6   4
[15,]   6   6   5
[16,]   6   6   4
[17,]   6   6   5
[18,]   6   6   4
[19,]   6   6   5
[20,]   6   6   1
```

And just to check that we're getting the probabilities we think we're getting:

```
cs = coda.samples( jagsModel , variable.names=parameters , 
                   n.iter=nIter , thin=thinSteps )

d <- do.call("rbind", cs)

d$di1 <- as.factor(d$di1)
d$di2 <- as.factor(d$di2)
d$di3 <- as.factor(d$di3)

cpt <- cpt(di3 ~ di1 + di2, data=d)

cpt[di1=6, di2=6, ]
```

```
         1          2          3          4          5          6 
0.14950980 0.10294118 0.02696078 0.27696078 0.41421569 0.02941176
```

The original probabilities defined in the construction of the training dataset were:

```
#di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
```

**Comment by jarrod-dalton** [comment]
Here's a solution that gets around the unnecessary sampling of all 36 combinations of di1 and di2:

```
model{
  # Likelihood:
  di1 ~ dcat(priorProbs)
  di2 ~ dcat(priorProbs)
  probs <- probArray[di1,di2,]
  di3 ~ dcat(probs)
}
```

```
cs = coda.samples( jagsModel , variable.names=parameters , 
                   n.iter=nIter , thin=thinSteps )

d <- as.data.frame(do.call("rbind", cs))

d$di1 <- as.factor(d$di1)
d$di2 <- as.factor(d$di2)
d$di3 <- as.factor(d$di3)

newCpt <- cpt(di3 ~ di1 + di2, data=d)
```

```
> newCpt[di1=6, di2=6, ]
         1          2          3          4          5          6 
0.12531333 0.10002426 0.01002668 0.33272014 0.41204415 0.01987143 
> cpt[di1=6,di2=6,]
          1           2           3           4           5           6 
0.125000000 0.098039216 0.009803922 0.333333333 0.414215686 0.019607843 
```

**Comment by jarrod-dalton** [comment]
What's left from here:

1) add `modelToNode.cpt()` method   **done**
2) add `setNodeModels.cpt()` method  **Not actually a generic**
3) add `writeJagsModel.cpt()` method **done**
4) add `writeJagsFormula.cpt()` method **done**

**Comment by nutterb** [comment]
```
n <- 50000 
data <- data.frame(
  di1=as.factor(1:6 %*% rmultinom(n,1,prob=c(.4,.3,.15,.10,.03,.02))),
  di2=as.factor(1:6 %*% rmultinom(n,1,prob=rev(c(.4,.3,.15,.10,.03,.02)))),
  di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
)
cpt <- HydeNet::cpt(di3 ~ di1 + di2, data)
```

I seem to be struggling with the concept here.

In the example above, would the node we define be `di3` with parents `di1` and `di2`?  I've been trying to figure out how to define the `cpt` node, and I can't even figure out how to get started.  So I'm really hoping it's a misconception and what I need to do is define the `di3` node and use the output of the `cpt` function to define the probability arrays that feed it.  Is that correct?

(that would be the first conceptual step...there are about 10 more I'm sure I need to take)

**Comment by jarrod-dalton** [comment]
Have time for a phone call?

(216) 210-5197

- Jarrod

**Comment by nutterb** [comment]
To get this put together, I had to make a few changes.
1. `cpt` and `inputCPT` are now generics with methods for `list` and `formula`.  It was a lot easier to tie things together when I could pass an argument named `formula` with the fitter function.
2. I also needed to attach the data to the object (like how `lm` and `glm` have `model` attributes with the data.  At this point, we have two options.  I can attach the data using `attr(cpt.object, "model") <- data`, or we can return the object as `list(cpt = cpt.object, model = data)`.  If we do the list, we'll need to define a `print.cpt` method.  Do you have a preference?
3. As requested, `HydeNetwork` will, by default, assign `cpt` as the fitter function when the node and all its parents are categorical.

The package is going to be buggy until I get the rest of the methods written, but I want to upload my work for now so you can see it.  As I was looking at the results of `inputCPT`, it seems that the object returned is different than the output from `cpt`.  Is that correct?  If so, is that by design?  I need to know if they should have different outputs and be treated differently, or if they should have the same output so that I can teach `HydeNet` how to handle them appropriately.

I'll open a new branch called 'devel-cpt` to upload these changes into and we can work on it from there.

**Comment by nutterb** [comment]
er...crap!  I just uploaded it to the `development` branch.  I'm a genius.  

But I have to go make dinner so I can't fix it right now.  Everything should run fine as long as you aren't using any `cpt` models, so I don't think I'll bother to revert. (at the very least, it passes `check` right up until the examples when it tries to create the JAGS code for a `cpt` model).

**Comment by jarrod-dalton** [comment]
Why do we need to attach the data to the object? Is there some use for it?

For now at least, I'd probably lean toward defining the data as an attribute of the `cpt` object.  As much as I hate using attributes (lists are cleaner in my view), writing the print method just seems extraneous (it's just an array - couldn't we default to the print method for multidimensional arrays?).

The output was supposed to be the same.  How is it different between `cpt()` and `inputCPT()`?  the `inputCPT()` function 1) goes through all the user input stuff, 2) creates a dataset with frequencies/probabiliites, then 3) invokes `cpt()`.  So it should return an object of class `cpt`, at least I think.

**Comment by nutterb** [comment]
I'll think over it.  I may not need to attach it, but I was trying to keep it a little more conformed to how the other model objects are constructed.  When I was writing it's method for `setNodeModel` I felt like there was some reason to have the data included, perhaps so that the user could have the option of refitting the model at some point in the process.

But you bring up a good point about the print method.  I can easily make the object a list and write a 
`print.cpt <- function(x, ...) print.array(x$cpt, ...)`

And you're right, the output isn't different.  I was misreading the code.  For some reason I thought `inputCPT` returned a list with elements `vars`, `data`, and `wt`.  So it does exactly what you intended it to do.  I'll just go work on my reading comprehension :)

**Comment by nutterb** [comment]
Nope.  Changed my mind again.  Making the `cpt` object a list would mean rewriting all of the subsetting functions (`[`, `[[`, etc), which I'm not interested in doing.  The data is included as an attribute.

**Comment by nutterb** [comment]
Oops.  Not closed.  My checklist of things to finish is in here.

**Comment by nutterb** [comment]
I think I've gotten myself confused here.

``` r
library(HydeNet)
n <- 50000
Di <- data.frame(
  di1=as.factor(1:6 %*% rmultinom(n,1,prob=c(.4,.3,.15,.10,.03,.02))),
  di2=as.factor(1:6 %*% rmultinom(n,1,prob=rev(c(.4,.3,.15,.10,.03,.02)))),
  di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
)

net <- HydeNetwork(~ di3 | di1*di2,
                   data = Di)
plot(net)

x <- cpt(di3 ~ di1 + di2, data = Di)

net <- setNodeModels(net, x)
net <- setNode(net, di1, nodeType = "dcat",
               nodeFitter = "xtabs",
               nodeFormula = ~ di1,
               fromData = TRUE,
               pi = fromData())
net <- setNode(net, di2, nodeType = "dcat",
               pi = fromData(),
               nodeFitter = "xtabs",
               nodeFormula = ~ di2,
               fromData = TRUE)

HydeNet:::writeJagsModel(net, "di3")
[1] "probs.di3 <- probArray.di3[pi.di1, pi.di2,]\n   di3 ~ dcat(probs.di3)"
```

Is this what the network model should look like?

```
writeNetworkModel(net, pretty=TRUE)
model{
   probs.di3 <- probArray.di3[pi.di1, pi.di2,]
   di3 ~ dcat(probs.di3)
   pi.di1[1] <- 0.39992; pi.di1[2] <- 0.30176; pi.di1[3] <- 0.14774; pi.di1[4] <- 0.10038; pi.di1[5] <- 0.02894; pi.di1[6] <- 0.02126
   di1 ~ dcat(pi.di1)
   pi.di2[1] <- 0.0198; pi.di2[2] <- 0.03044; pi.di2[3] <- 0.10064; pi.di2[4] <- 0.15104; pi.di2[5] <- 0.29834; pi.di2[6] <- 0.39974
   di2 ~ dcat(pi.di2)
}
```

And if that seems right, how do we get the proabability array into JAGS?

```
compileJagsModel(net, data=list(probArray.di3 = net$nodeModel[["di3"]]))
Compiling model graph
   Resolving undeclared variables
   Allocating nodes
Deleting model

Error in rjags::jags.model(textConnection(writeNetworkModel(network)),  : 
  RUNTIME ERROR:
Compilation error on line 2.
Unknown parameter probArray.di3

In addition: There were 36 warnings (use warnings() to see them)
```

**Comment by jarrod-dalton** [comment]
So the model block should look more like this:

```
model{
  # Likelihood:
  di1 ~ dcat(priorProbs)
  di2 ~ dcat(priorProbs)
  di3.probs <- di3.cpt[di1,di2,]
  di3 ~ dcat(probs)
}
```

The `di3.cpt` object should get passed to JAGS as a list element to the `data =` parameter in `jags.model()`.

So my thought is that the `cpt` object gets attached to the `HydeNetwork` `di3` node using a standard naming of _nodeName.cpt_ (i.e., `di3.cpt`), and then somehow gets passed into the `data =` parameter in `compileNetworkModel()` (or wherever it's appropriate - can't remember).

**Comment by nutterb** [comment]
Maybe I'm being thick, but how is your model statement different than mine?

(The order of the variables shouldn't matter, and mine are out of order because of the way `HydeNetwork` put together the network object.)

**Comment by jarrod-dalton** [comment]
Sorry - they are the same indeed.  (Though you could pass the probabilities as 1-d arrays for di1 and di2.)

Were you able to get it working by passing the array as a list element to `jags.model(data=)`?

**Comment by nutterb** [comment]
I tried passing the array object but I'm getting weird cryptic messages. I'm kind of at a loss.  I can't find any good tutorials or examples of how to pass probability arrays to JAGS either.  and in general, technology hates me today </whine>

**Comment by jarrod-dalton** [comment]
I don't know if this helps, but it is a complete, stand-alone script that works.

Regarding your frustrations with JAGS, that's why we're doing this project. 

```
n <- 50000 
data <- data.frame(
  di1=as.factor(1:6 %*% rmultinom(n,1,prob=c(.4,.3,.15,.10,.03,.02))),
  di2=as.factor(1:6 %*% rmultinom(n,1,prob=rev(c(.4,.3,.15,.10,.03,.02)))),
  di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
)
cpt <- HydeNet::cpt(di3 ~ di1 + di2, data)


dataList = list(
  priorProbs = c(rep(.001->ppp,5),1-ppp),  #rep(1,6),
  di3.cpt = cpt
)


fc <- textConnection(
"
model{
  # Likelihood:
  di1 ~ dcat(priorProbs)
  di2 ~ dcat(priorProbs)
  di3.probs <- di3.cpt[di1,di2,]
  di3 ~ dcat(di3.probs)
}
"
)

jagsModel <- jags.model(fc , data=dataList , # inits=initsList , 
                        n.chains=3 , n.adapt=1000 )


cs <- coda.samples( jagsModel , variable.names=c("di1","di2","di3") , 
                    n.iter=1000  )

cs <- as.data.frame(do.call("rbind", cs))

dplyr::sample_n(cs, 15)
```

```
     di1 di2 di3
2657   6   6   5
2089   6   6   5
983    6   6   4
1638   6   6   5
2981   6   6   4
2804   6   6   5
1060   6   6   4
1287   6   6   5
998    6   6   1
1697   6   6   6
313    6   6   1
114    6   6   4
28     6   6   2
494    6   6   1
2414   6   6   6
```

**Comment by nutterb** [comment]
Crisis averted...sort of.  The problem isn't JAGS.  When I copy and paste my JAGS code to try to run it without HydeNet, it works just fine.

The problem is in `compileJagsNetwork` on line 87 where I have written

```
if (is.list(data)) data <- as.data.frame(data)
```

I'm losing my array when I try to force the data list into a data frame (for no good reason, I might add).  Let me try taking that line out and seeing if everything still works (which it should).

**Comment by nutterb** [comment]
Mission Accomplished:

```
library(HydeNet)
n <- 50000
Di <- data.frame(
  di1=as.factor(1:6 %*% rmultinom(n,1,prob=c(.4,.3,.15,.10,.03,.02))),
  di2=as.factor(1:6 %*% rmultinom(n,1,prob=rev(c(.4,.3,.15,.10,.03,.02)))),
  di3=as.factor(1:6 %*% rmultinom(n,1,prob=c(.15,.10,.02,.3,.4,.03)))
)

net <- HydeNetwork(~ di3 | di1*di2,
                   data = Di)
plot(net)

x <- cpt(di3 ~ di1 + di2, data = Di)

net <- setNodeModels(net, x)
net <- setNode(net, di1, nodeType = "dcat",
               nodeFitter = "xtabs",
               nodeFormula = ~ di1,
               fromData = TRUE,
               pi = fromData())
net <- setNode(net, di2, nodeType = "dcat",
               pi = fromData(),
               nodeFitter = "xtabs",
               nodeFormula = ~ di2,
               fromData = TRUE)

HydeNet:::writeJagsModel(net, "di3")
writeNetworkModel(net, pretty=TRUE)

j <- compileJagsModel(net)

post <- HydePosterior(j, c("di1", "di2", "di3"), n.iter=100)
post <- bindPosterior(post)
prop.table(table(post$di1))
prop.table(table(post$di2))
prop.table(table(post$di3))
```

**Comment by jarrod-dalton** [comment]
Trying to understand your code...aren't you doing the same thing twice?  Doesn't passing the dataset to HydeNetwork take care of setting the node distributions?  

```
net <- HydeNetwork(~ di3 | di1*di2,
                   data = Di)
plot(net)

x <- cpt(di3 ~ di1 + di2, data = Di)

net <- setNodeModels(net, x)
net <- setNode(net, di1, nodeType = "dcat",
               nodeFitter = "xtabs",
               nodeFormula = ~ di1,
               fromData = TRUE,
               pi = fromData())
net <- setNode(net, di2, nodeType = "dcat",
               pi = fromData(),
               nodeFitter = "xtabs",
               nodeFormula = ~ di2,
               fromData = TRUE)
```

**Comment by nutterb** [comment]
I think you're right. I originally hadn't used the data argument when I started a d put it in closer to the end. The set Node calls might be redundant

**Comment by jarrod-dalton** [comment]
So, we have a complete Bayesian network analysis (ignoring diagnostics) in 4 lines of R code. 5 lines if you want to visualize the network.

```
net <- HydeNetwork(~ di3 | di1*di2,  data = Di)
j <- compileJagsModel(net)
post <- HydePosterior(j, c("di1", "di2", "di3"), n.iter=100)
post <- bindPosterior(post)
```

Pretty neat stuff!
