### ISSUE TITLE
working with cpt classes is annoying

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#66]
...because the source data is attached as an attribute called `model`.

When I try to call it with a dataset having 10000 rows, and want to see what the array looks like, all I get in the console is the last several hundred rows of the model attribute.

Do we **REALLY** need to attach the source data?  I can't find a use for it!

**Comment by nutterb** [comment]
I figured out a way to add a print method to avoid this problem without affecting the subsetting functions.
