### ISSUE TITLE
Do we still depend on Rgraphviz?

### ISSUE THREAD

**Issue by jarrod-dalton** [nutterb/HydeNet#71]
Running the vignette on my work PC tells me that the package is required but not installed.

**Comment by nutterb** [comment]
`HydeNet` doesn't depend on it directly.  `HydeNet` imports from `graph`, which suggests `Rgraphviz`.  When a package is installed, all the packages for its dependencies, imports, and suggests are also installed (as well as all of their dependencies).  So when you try to install `HydeNet` it will want to install `Rgraphviz`. 

This won't be an issue when installing from CRAN, as CRAN automatically looks to Bioconductor when it can't find a package on CRAN.  When installing from GitHub, we need to tell R to also look at Bioconductor by using 

``` r
setRepositories(ind=1:2)
```

This is included in the `Getting Started` vignette.  We may want to consider adding that to the README file as well.

**Comment by jarrod-dalton** [comment]
I did that, and it gives me the error message. So I installed using the script provided on the Bioconductor website (i.e., via `bioclite`).  It asked me if I wanted to update a bunch of other packages, so I said 'y'.

So I'm not sure what's going on there.

**Comment by nutterb** [comment]
I'm going to guess that you are doing the same confusing thing I just did to try and replicate your error.

Try using:

``` r
setRepositories(ind=1:2)
devtools::install_github("nutterb/HydeNet", ref = "development")
```

Without the `ref` argument, you're installing the old version of `HydeNet` that lives in the master branch, and that older version does depend on `Rgraphviz`.  Sorry for the confusion.

**Comment by jarrod-dalton** [comment]
Duh.

**Comment by nutterb** [comment]
Don't worry.  I do it all the time.
