### ISSUE TITLE
Register `HydeNet` with Zenodo

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#80]
How would you feel about registering the package with Zenodo?  This would provide us with a DOI (digital object identifier) to be used in publications.

www.zenodo.org

**Comment by jarrod-dalton** [comment]
I can't say I have an opinion. What are the advantages of having a DOI?  Go for it if you want.
- Jarrod

**Comment by jarrod-dalton** [comment]
Do you know if doing this would prevent us from publishing an article with the package, say in the Journal of statistical software?
- Jarrod

**Comment by nutterb** [comment]
I honestly don't know, and the answer may vary by journal. I will hold off on this until the manuscript is under review and we can ask the publisher.
