### ISSUE TITLE
Store network images in vignettes as PNGs

### ISSUE THREAD

**Issue by nutterb** [nutterb/HydeNet#84]
The `DiagrammeR` images are pretty big, and the CRAN check keeps giving a NOTE that there are directories larger than 1Mb (it's 13 Mb).  To make the CRAN checks easier, I'm going to store the images in the stable vignettes as PNGs and read them in from the `inst` directory.  This will allow the package to install faster as well.

**Comment by nutterb** [comment]
When I tried to store the images as PNG files, the final files got larger.  I think we really only have two options:
1. Leave the vignettes as they are and deal with the large download size
2. Fix up a `HydeNet` web site and store the vignettes there.  Then build a single vignette for the package with links to the vignettes on the web site.

I'm going to send an e-mail to CRAN to ask them if they have a preference.  If it were a little over the 1Mb recommendation, I'd just deal with it being large, but at 13 Mb, I'd like to get their input.

**Comment by jarrod-dalton** [comment]
What if we tried the JPG format? I have IrfanView image software if you need help converting the files. Just point me to the PNG (or whatever) file locations.
- Jarrod

**Comment by nutterb** [comment]
I didn't save the PNG files long enough to push them to the repository.  All I did was export them from the viewing pane using R Studio's export tool.  Could you try running `plot(BlackJack)` and converting that to a JPG.  How large is the file?

**Comment by jarrod-dalton** [comment]
Just uploaded a .tif file I created by taking screen shot of the network.
Not the most elegant technique, but oh well.  The file size is 230Kb. Does
the plot look okay? How does it render in the vignette?

**Comment by nutterb** [comment]
The tif looked okay.  I worked some more on it last night and managed to get some JPEG (TIF wasn't an option on my home computer for some reason), but got reasonably sized images.  The vignettes are now small enough to pass the check.
