### ISSUE TITLE
Default behavior of HydeNetwork() w/ Training Dataset

### ISSUE THREAD

**Issue by j-e-dalton** [nutterb/HydeNet#9]
See the dataset PE I inserted in the package.

I'm getting a rather cryptic error message:

> data(PE, package='Hyde')
> net <- HydeNetwork(~ wells
> -                    + pe | wells
> -                    + d.dimer | pregnant*pe
> -                    + angio | pe
> -                    + treat | d.dimer*angio
> -                    + death | pe*treat,
> -                    data = PE)
>   Error in `[[<-`(`*tmp*`, which(sapply(nodeFitter, function(x) x == "glm")),  : 
>   no such index at level 2
>   head(PE)
>   wells pregnant  pe    angio d.dimer treat death
>   1     3       No  No Negative     206    No    No
>   2     2       No  No Positive     180   Yes    No
>   3     3       No  No Negative     197    No    No
>   4     3       No  No Negative     192   Yes    No
>   5     2       No  No Negative     281   Yes    No
>   6     6       No Yes Positive     318   Yes    No

**Comment by nutterb** [comment]
Resolved. I had to remove a set of brackets to use `[` instead of `[[`.
