### ISSUE TITLE
Changes in upcoming v0.8 release of `DiagrammeR` package will require changes in `plot.HydeNetwork`

### ISSUE THREAD

**Issue by rich-iannone** [nutterb/HydeNet#93]
I'm planning on releasing a new version of `DiagrammeR` to CRAN but some important changes to your `plot.HydeNetwork` function will be required.

The node ID column in a node data frame is now named `nodes`. Please change in any instances of `node_id` to `nodes` when referencing a node data frame.

In edge data frames, column names for node IDs were simplified to `from` and `to`. Please change in any instances of `edge_from` to `from` and `edge_to` to `to` when referencing an edge data frame.

I think that is it. Also ensure that version 0.8 or higher is specified in the `DESCRIPTION` file. Please let me know if there are any questions about this.

**Comment by nutterb** [comment]
Thanks for letting me know, Rich.  I'll get these updated this weekend.  What's your timeline on releasing to CRAN. I've been preparing to release a new version of `HydeNet`, but at this point, I may be better off waiting until `Diagrammer` goes up.

**Comment by rich-iannone** [comment]
Thanks for the quick response!

I just submitted the package right now. Hopefully this doesn't cause too much frustration for users in between versions. However, this will be the last time I change column names.

**Comment by nutterb** [comment]
Updated and currently submitting.
